### ISSUE TITLE
개발 환경 관련

### ISSUE THREAD

**Issue by HoneyGGuri** [rnin9/db_application_2020_KW#1]
[개발 환경.xlsx](https://github.com/rnin9/db_application_2020_KW/files/5345581/default.xlsx)
![image](https://user-images.githubusercontent.com/51199690/95420783-14397480-0977-11eb-93ea-801b88bb99eb.png)

각 개발 환경, 프레임워크 간단하게 정리해봤습니다. 조금씩 틀린 점이 있을 수 있습니다.
이미지 클릭하시면 원본 크기로 볼 수 있습니다.

다음 주 회의 때까지 개발 환경 확정을 지어야하니 결정하는데 있어서 참고용으로 생각해주세요.

**Comment by rnin9** [comment]
### React
___
기존에 제가 사용해봤던 React에 대하여 참고하면 좋을 문서가 있어, 링크를 걸어드립니다. 

### [React를 사용하는 이유](https://velog.io/@youthfulhps/React-React%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)


배포에 대한 부분은 저희가 local에서 진행할 계획이므로, 딱히 신경쓰지 않아도 될 부분일 것 같습니다.

**Comment by rnin9** [comment]
#1 **React**
___

기존에 제가 사용해봤던 React에 대하여 참고하면 좋을 문서가 있어, 링크를 걸어드립니다. 


 **[React를 사용하는 이유](https://velog.io/@youthfulhps/React-React%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)**

**Comment by Oh-0-honey** [comment]
![ER 모델](https://user-images.githubusercontent.com/51199690/98382784-fc94ff00-208e-11eb-9cf6-6a09b9354ed5.JPG)

**Comment by HoneyGGuri** [comment]
![ER 모델](https://user-images.githubusercontent.com/51199690/98382977-40880400-208f-11eb-8e80-8f099dbe8d5a.JPG)
