### ISSUE TITLE
기능 개발 관련

### ISSUE THREAD

**Issue by HoneyGGuri** [rnin9/db_application_2020_KW#2]
### 기본 주제는 "학생 정보 관리 시스템"으로 아래는 기본 기능들입니다.

1. 회원 가입
2. 개인 정보 조회
3. 강의시간표 조회
4. 수강신청
5. 과목별 공지사항 게시판
6. 학습결과(수강/성적 조회)
6-1. 학기별 성적 추이, 전공/교양 별 성적 분포 그래프

### 여기에 추가할 **독창적인 부분**을 생각해주세요.
**과제 pdf에 적혀있는 예시**
1. 친구와 강의 시간표 공유
2. 학점 비교
3. 강의 평가 순 정렬

**Comment by HoneyGGuri** [comment]
### 오영헌
**디자인쪽 보단 SQL문 기능 위주로 생각해보았습니다.**
1. 강의 평가 기능
1-1. 별점+코멘트(에브리타임 강의평가 느낌으로)
1-2. 태그 기능(ex. #중간고사없음, #인강, #영어수업, #팀플, #F폭격기, #연강, #일찍끝남, #지루함, #발표 같은)
1-3. 평가에 대해 추천, 비추천 가능
2. 강의 평가 조회
2-1. 별점순 조회
2-2. 태그별 조회 
3. 수강신청 할 때 수업 추천 기능(전공 선수과목, 기수강 교양과 비슷한 수업, 인기 많은 수업, 자리가 널널한 수업)
4. 강의 검색 기능
5. 강의명, 교수명, 교과목에 따른 뷰 순환
6. 교수나 관리자로 로그인하면 수업 추가, 삭제 할 수 있게끔
7. 학생은 게시판에서 자기 글만 삭제 가능. 교수, 관리자는 학생글을 삭제 가능

**Comment by rnin9** [comment]
#2  강민주

추가적으로 독창성 부분에서 제가 생각한부분은 다음과 같습니다 .

**1. 강의평가 순 정렬**
  * 강의 평가에서,전공별, 성별, 전체 기준으로 인기도를 확인하여, 순위별로 1~5등까지 보여주는 페이지를 구현하면, 좀더 간단히 페이지를 구성할 수 있을것 같습니다. 
 
 **2. 공지사항 페이지** 
* 공지사항을  최신 순으로,  일반 공지사항과 과제 / 긴급과 같은 공지사항을 알려줄 수 있는 UI 적인 design을 추가해보면 어떨까 싶습니다. 

**3. 신고 기능** 
* 오영헌씨가 생각한 7. 문항에서, 신고기능을 추가하여 관리하는게 삭제를 구현하는 것보다 편하지 않을까 합니다. 
* EveryTime을 볼 때, 작성후 변경 자체는 불가능 하도록 되어있고, 신고를 통해 관리하고 있습니다. admin, 학생, 교수님 3개의
권한을 가지고 나누는 것보다, 구현이 쉬워질듯 합니다.

**Comment by meltnia** [comment]
이영주입니다.

1. **과목별 평가 수치를 따져서 어떠한 분야에 대한 능력 평가를 하기**
예를 들어, 객체지향프로그래밍, 데이터베이스, 심리학, 인공지능, 물리, 영상처리라는 과목이 있다고 할 때,

객체지향프로그래밍 => 프로그래밍 5, 설계능력 3
데이터베이스 => 프로그래밍 3, 설계능력 5
인공지능 => 프로그래밍 1, 설계능력  5, 구상능력 3
물리 => 과학지식(물리) 5, 실험능력 3
영상처리 => 프로그래밍 4, 설계능력 4

이런식으로 배정되어 있다고 가정하고, 이를 수강한 학생이 있을 때, 받은 학점을 배정된 계수들에 곱하고 합하여서 학생의 능력을 그래프로 보여주며 이러한 직군에 알맞은 거 같습니다. 라는 식의 기능을 구상해보았습니다.

ex) 객체지향 프로그래밍 A, 데이터베이스 B, 영상처리 A, 물리 F의 경우,
프로그래밍 점수 : 5 x 4 + 3 x 3 + 4 x 4 = 45
설계능력 점수 : 3 x 4 + 5 x 3 + 4 x 4 = 43
과학지식(물리) 점수 : 5 x 0  = 0
실험능력 점수 : 3 x 0  = 0

**Comment by HoneyGGuri** [comment]
> **3. 신고 기능**
> 
> * 오영헌씨가 생각한 7. 문항에서, 신고기능을 추가하여 관리하는게 삭제를 구현하는 것보다 편하지 않을까 합니다.
> * EveryTime을 볼 때, 작성후 변경 자체는 불가능 하도록 되어있고, 신고를 통해 관리하고 있습니다. admin, 학생, 교수님 3개의
>   권한을 가지고 나누는 것보다, 구현이 쉬워질듯 합니다.

제가 말했던 7. 게시판 기능은 강의평가가 아니라 공지사항같은 수업 게시판을 말했었습니다.

**Comment by rnin9** [comment]
### 기본기능
___
* 회원가입 및 개인 정보 조회

  * 회원가입
  * 권한 별 정보 조회

* 강의시간표 조회

  * 년도, 학기, 전공, 교양에 따른 시간표 조회

* 수강신청 기능
### 고급기능
___

* 친구 기능
  *  시간표/성적 공유 기능

* 과목별 공지사항 게시판

  * 과목에 대한공지, 과제에 대한 공지

*  학습결과 (수강/성적 조회) - 학기별 성적 추이 그래프

   * 전공 및 교양 별 성적 분포 그래프

* 휴학생 관리 기능

  * 휴학생 정보 출력
  * 제적 정보 출력

* 강의 평가 기능 
  * 강의 분석
  * 좋아요 기능
