### ISSUE TITLE
User

### ISSUE THREAD

**Issue by rnin9** [rnin9/db_application_2020_KW#3]
사용자에 관련된 Relation입니다.

**Comment by meltnia** [comment]
고유 id : 단순하게 들어온순서로 하든, 뭐로 하든 외부에 들어나지 않는 id
외부 id : 개개인이 정한 id(닉네임)
권한 수준 : admin인지 아닌지 표기하기 위한 1bit, 아니면 학년같은 것을 표현할 것이면 아예 3bit로 해서 1~5를 일반학생으로 하고, 7을 관리자로 하는것도 가능하리라 생각합니다.
table id : 자신의 시간표 테이블에 연결하기 위한 table 번호

이렇게 생각해봤습니다.

**Comment by rnin9** [comment]
**제안 사항**
___
- Attribute로 생각한 부분입니다.
```
- 아이디(ID)
- 비밀번호(password)
- 전공(Major)
- 성별(Gender)
- 학년(Grade?)
- 이메일(email)
```

- 학년의 이름을 Grade로 생각할 것인지에 대해서는 생각해봐야 할 부분일 것 같습니다 (Join시 문제)
- password에 대한 부분을 암호화 하는 것 또한 독창성에 추가할 수 있는 부분일 것 같습니다

**추가 사항**
___

>  고유 id : 단순하게 들어온순서로 하든, 뭐로 하든 외부에 들어나지 않는 id
>  외부 id : 개개인이 정한 id(닉네임)


- ID를 이메일로 할 것인지, 혹은 email과 ID를 분리 할 것인지 생각해야 할것 같습니다. ID는 Primary Key로서 사용될 수 있기에,
고유, 외부 ID에 대한부분을 생각해봐야 할 것 같습니다.

**Comment by meltnia** [comment]
외부 ID의 경우 말그대로 닉네임같은 것으로 사용하는 용도로 생각한 것이라 필요 없다고 생각되면 제외하면 될 것이라 생각합니다.

**Comment by HoneyGGuri** [comment]
- 제가 생각한 Attribute입니다.
```
- 아이디(= 학번)
- 비밀번호
- 이름
- 학부(단과대학)
- 전공
- 성별
- 학년
- 분류
- 성적 공개 여부
- 시간표 공개 여부
- 이메일
- 전화번호
- 주소
```

일단 구색상 필요한 것들은 생각나는대로 넣었습니다.

'분류'는 학생, 교수, 직원? 같은걸 구분하기 위해 생각해봤고
'성적/시간표 공개 여부'는 친구로 등록된 사람한테 내 시간표/성적을 공개 할 것인지 여부입니다.

로그인은 아이디(학번)으로 하고 수업 게시판, 수업 평가 등에서 노출되는건 그냥 실명, 필요에 따라 익명으로 하면 되지 않을까 싶네요.
학년은 'm학년 n학기' 같이 표현할꺼면 Semester 같이 학기라고 표현해도 괜찮을 것 같습니다.

**Comment by HoneyGGuri** [comment]
xx년 x학기에 학교를 다녔다. oo년 o학기에 휴학을 했다. 같은 정보는 필요 없을까요?

**Comment by rnin9** [comment]
```
CREATE TABLE User(
    userID varchar(30) not null,            // 학번, 로그인 시 사용하는 ID
    password varchar(30) not null,
    userName varchar(30) not null,
    college varchar(30) not null,           // 단과대학
    major varchar(30) not null,
    gender varchar(10) not null,
    grade int not null check (grade >0 AND grade <6),
    position varchar(20) not null,          // 분류 = (교수, 학생, 직원)
    email varchar(50) ,
    phoneNumber varchar(30),
    address varchar(30), not null, 
    CONSTRAINT PRIMARY KEY(userID) );  
```

>Q . 혹시 user쪽 id 타입을 어떻게 정하셨는지 들을 수 있을까요?
>-  해당부분이 grade와 겹칠 수 있다고 판단하여, varchar(30)으로 변경해야 할 것 같습니다.

> Q. xx년 x학기에 학교를 다녔다. oo년 o학기에 휴학을 했다. 같은 정보는 필요 없을까요?
>- 휴학생에 관련된 Schema를 만들어 관리하는방식은 어떨까요?

>Q.  '성적/시간표 공개 여부'는 친구로 등록된 사람한테 내 시간표/성적을 공개 할 것인지 여부입니다.
>- 해당부분은 bool로 표현하게 된다면, 모든사람 기준으로 저장이 될 것 같아 일단 추가하지 않았고, 같이 상의해야할 부분 같습니다. 개인적인 의견으로는 친구를 맺게 되는 경우, Friend Schema를 구성하여 따로 해당 부분을 관리할 수 있게하면 직관적으로 이해 할 수 있을것 같습니다.

**Comment by rnin9** [comment]
**완성된 User테이블 입니다**

```
CREATE TABLE USER(
    userID varchar(30) not null,            // 학번, 로그인 시 사용하는 ID
    userPassword varchar(30) not null,
    userName varchar(30) not null,
    userPhoto varchar(30),                  // 사용자 사진
    userCollege varchar(30) not null,           // 단과대학
    userMajor varchar(30) not null,
    userGender varchar(10) not null,
    userGrade int not null check (grade >0 AND grade <6),
    userPosition varchar(20) not null,          // 분류 = (교수, 학생, 직원)
    userEmail varchar(50),
    userPhoneNumber varchar(30),
    userAddress varchar(30) not null, 
    leaveOfAbsense bool default FALSE not null,
    CONSTRAINT PRIMARY KEY(userID) );  
```

leaveOfAbsense를 통해서 휴학상태를 알려 줄 수 있는 attribute를 추가했습니다.
