### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by rnin9** [rnin9/db_application_2020_KW#6]
공지사항에 관련된 Relation입니다.

**Comment by rnin9** [comment]
**제안 사항**
___
- Attribute로 생각한 부분입니다.
```
- 공지 게시자(Name)
- 공지 날짜(Date)
- 공지 내용(Content)
- 공지 범주(Criteria) = 과제/긴급/New ..
```

- 공지날짜에 대한 부분은 desc를 이용한(최신 순) sql로 나타낼 수 있을 듯 합니다.
- 공지범주에 대한 정의가 필요할 것 같습니다.

**Comment by HoneyGGuri** [comment]
- 내용 외에 첨부파일을 다루는 부분도 필요한 것 같습니다.
- 범주의 경우 유저 분류(학생/교수)에 따라
  - 학생 : 일반, 질문, 기타 등등
  - 교수 : 일반, 과제, 긴급, ...
같이 나누면 어떨까요

**Comment by rnin9** [comment]
```
CREATE TABLE Notice(
    noticeID int not null auto increment,         // 고유 ID
    noticeName varchar(30) not null,
    noticeDate date not null,
    noticeContent varchar(1000) not null,
    filename varchar(50),                         // 첨부파일
    position varchar(30) not null,                // 범주를 다르게 하기 위한 직급 FK => 참조
    criteria int not null,                        // 범주
    CONSTRAINT PRIMARY KEY(NoticeID) ); 
```

>  Q. 내용 외에 첨부파일을 다루는 부분도 필요한 것 같습니다.
>> * filename으로 해결하였습니다.

>  Q. 범주의 경우 유저 분류(학생/교수)에 따라
>   
>   * 학생 : 일반, 질문, 기타 등등
>   * 교수 : 일반, 과제, 긴급, ...
>     같이 나누면 어떨까요
>>  * 영헌이 의견을 받아 position별로 criteria의 1, 2, 3을 다르게 구성하도록 attribute를 구성했습니다.
>>    * ex)  Position = '교수'  , Criteria 1 = 일반 , 2 = 과제, 3 =긴급
           Position = '학생'  , Criteria 1 = 질문,  2 = 기타

filename table =>

**Comment by rnin9** [comment]
**완성된 Notice TABLE 입니다**
```
   CREATE TABLE NOTICE(
    noticeID int not null auto_increment PRIMARY KEY,
    noticeName varchar(30) not null,
    userID varchar(30) not null,
    noticeDate date not null,
    noticeWriter varchar(30) not null,
    noticeContent varchar(1000) not null,
    noticeFiles bool,
    position varchar(20) not null,                
    criteria int not null,                        
    CONSTRAINT FK_NT_WRITER
    FOREIGN KEY(userID) REFERENCES USER(userID)
);
```

* 작성자 이름을 추가하기위해, FK noticeWriter를 사용하였습니다.
* 첨부 파일은 Notice_files table에서 관리합니다.
* noticeFiles을 통해 첨부파일이 존재하는지 확인합니다.

**Comment by rnin9** [comment]
* 조금더 생각해봤는데, FK로 가져오는 둘 ( noticeWriter , position )의 check ( 이름과 권한이 일치하는지 )가 필요하기 때문에, 해당 부분을 FK로 이용하기보다 ID를 통해 Join을 진행 하는게 좀 더 쉬운 방법일거 같습니다.

따라서 아래와 같이 구성했습니다.

```
CREATE TABLE Notice(
    noticeID int not null auto increment PRIMARY KEY,         // 고유 ID
    userID varchar(30) not null,
    noticeName varchar(30) not null,
    noticeDate date not null,
    noticeWriter varchar(30) not null,
    noticeContent varchar(1000) not null,
    position varchar(30) not null,                // 범주를 다르게 하기 위한 직급 FK => 참조
    criteria int not null,                        // 범주
    ); 
```
